# Generated by Django 5.1.2 on 2024-11-20 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_walkinpatient_request_walk_in_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="walkinpatient",
            name="blood_type",
        ),
        migrations.RemoveField(
            model_name="walkinpatient",
            name="contact_number",
        ),
        migrations.RemoveField(
            model_name="walkinpatient",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="walkinpatient",
            name="email",
        ),
        migrations.RemoveField(
            model_name="walkinpatient",
            name="name",
        ),
        migrations.AddField(
            model_name="request",
            name="source",
            field=models.CharField(
                choices=[("online", "Online"), ("walkin", "Walk-in")],
                default="online",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="walkinpatient",
            name="blood_group",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="walkinpatient",
            name="county",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="walkinpatient",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="walkinpatient",
            name="firstname",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="walkinpatient",
            name="lastname",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="walkinpatient",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="walkinpatient",
            name="user_uuid",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="users.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="walkinpatient",
            name="gender",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
