# Generated by Django 5.1.2 on 2024-11-20 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0029_remove_walkinpatient_blood_type_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WalkInPatient",
            new_name="WalkInDonor",
        ),
        migrations.RemoveField(
            model_name="request",
            name="source",
        ),
        migrations.RemoveField(
            model_name="request",
            name="walk_in_patient",
        ),
        migrations.AddField(
            model_name="donation",
            name="source",
            field=models.CharField(
                choices=[("online", "Online"), ("walkin", "walkin")],
                default="online",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="walk_in_patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.walkindonor",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="users.userprofile",
            ),
        ),
    ]
