# Generated by Django 5.1.2 on 2024-11-20 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0030_rename_walkinpatient_walkindonor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="walk_in_patient",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="source",
        ),
        migrations.AlterField(
            model_name="donation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="users.userprofile",
            ),
        ),
        migrations.DeleteModel(
            name="WalkInDonor",
        ),
    ]
