# Generated by Django 5.1.2 on 2024-11-20 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0031_remove_donation_walk_in_patient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="users.userprofile",
            ),
        ),
    ]
